version: '3'

services:
  # Apache Spark
  spark-master:
    image: bigdataspark
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_MASTER_WEBUI_PORT=8080
      - SPARK_DRIVER_MEMORY=4g
      - SPARK_MASTER_LOG_DIR=/mnt/logs
    volumes:
      - .:/mnt


  spark-worker-1:
    image: bigdataspark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=2g
    depends_on:
      - spark-master
    volumes:
      - .:/mnt

  spark-worker-2:
    image: bigdataspark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=2g
    depends_on:
      - spark-master
    volumes:
      - .:/mnt

  # Apache Kafka
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    volumes:
      - .:/mnt

  kafka:
    image: bigdatakafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://:9093,OUTSIDE://:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    depends_on:
      - zookeeper
    volumes:
      - .:/mnt

  # MongoDB
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - .:/mnt

  # Dashboard app (assuming it's a web app)
  dashboard-app:
    image: bigdatadash
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
      - kafka
      - spark-master
    volumes:
      - .:/mnt
